kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: read-cat-manifest
    labels:
        # Add these permissions to the "view" default role.
        rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups: ["kearos.net"]
  resources: ["manifests"]
  verbs: ["get", "list", "watch"]
