kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: read-cat-manifest
subjects:
- kind: ServiceAccount
  name: cat-controller
  namespace: default
roleRef:
    kind: ClusterRole
    name: read-cat-manifest
    apiGroup: rbac.authorization.k8s.io
