apiVersion: v1
kind: ServiceAccount
metadata:
    labels:
        app: {{ template "cat-controller.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
    name: cat-controller
